#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEV_PhanTIch
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="\"QL_NhaThuoc\"")]
	public partial class DataThuocDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTHoaDonNhap(CTHoaDonNhap instance);
    partial void UpdateCTHoaDonNhap(CTHoaDonNhap instance);
    partial void DeleteCTHoaDonNhap(CTHoaDonNhap instance);
    partial void InsertThuoc(Thuoc instance);
    partial void UpdateThuoc(Thuoc instance);
    partial void DeleteThuoc(Thuoc instance);
    partial void InsertCTHoaDonXuat(CTHoaDonXuat instance);
    partial void UpdateCTHoaDonXuat(CTHoaDonXuat instance);
    partial void DeleteCTHoaDonXuat(CTHoaDonXuat instance);
    partial void InsertHoaDonNhap(HoaDonNhap instance);
    partial void UpdateHoaDonNhap(HoaDonNhap instance);
    partial void DeleteHoaDonNhap(HoaDonNhap instance);
    partial void InsertHoaDonXuat(HoaDonXuat instance);
    partial void UpdateHoaDonXuat(HoaDonXuat instance);
    partial void DeleteHoaDonXuat(HoaDonXuat instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhomThuoc(NhomThuoc instance);
    partial void UpdateNhomThuoc(NhomThuoc instance);
    partial void DeleteNhomThuoc(NhomThuoc instance);
    #endregion
		//
		public DataThuocDataContext() : 
				base(global::DEV_PhanTIch.Properties.Settings.Default._QL_NhaThuoc_ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataThuocDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataThuocDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataThuocDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataThuocDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTHoaDonNhap> CTHoaDonNhaps
		{
			get
			{
				return this.GetTable<CTHoaDonNhap>();
			}
		}
		
		public System.Data.Linq.Table<Thuoc> Thuocs
		{
			get
			{
				return this.GetTable<Thuoc>();
			}
		}
		
		public System.Data.Linq.Table<CTHoaDonXuat> CTHoaDonXuats
		{
			get
			{
				return this.GetTable<CTHoaDonXuat>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonNhap> HoaDonNhaps
		{
			get
			{
				return this.GetTable<HoaDonNhap>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonXuat> HoaDonXuats
		{
			get
			{
				return this.GetTable<HoaDonXuat>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhomThuoc> NhomThuocs
		{
			get
			{
				return this.GetTable<NhomThuoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHoaDonNhap")]
	public partial class CTHoaDonNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD_Nhap;
		
		private string _ma_thuoc;
		
		private System.Nullable<int> _gia_von;
		
		private System.Nullable<int> _SL_Nhap;
		
		private EntityRef<Thuoc> _Thuoc;
		
		private EntityRef<HoaDonNhap> _HoaDonNhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHD_NhapChanging(string value);
    partial void OnmaHD_NhapChanged();
    partial void Onma_thuocChanging(string value);
    partial void Onma_thuocChanged();
    partial void Ongia_vonChanging(System.Nullable<int> value);
    partial void Ongia_vonChanged();
    partial void OnSL_NhapChanging(System.Nullable<int> value);
    partial void OnSL_NhapChanged();
    #endregion
		
		public CTHoaDonNhap()
		{
			this._Thuoc = default(EntityRef<Thuoc>);
			this._HoaDonNhap = default(EntityRef<HoaDonNhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD_Nhap", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD_Nhap
		{
			get
			{
				return this._maHD_Nhap;
			}
			set
			{
				if ((this._maHD_Nhap != value))
				{
					if (this._HoaDonNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHD_NhapChanging(value);
					this.SendPropertyChanging();
					this._maHD_Nhap = value;
					this.SendPropertyChanged("maHD_Nhap");
					this.OnmaHD_NhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_thuoc", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma_thuoc
		{
			get
			{
				return this._ma_thuoc;
			}
			set
			{
				if ((this._ma_thuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_thuocChanging(value);
					this.SendPropertyChanging();
					this._ma_thuoc = value;
					this.SendPropertyChanged("ma_thuoc");
					this.Onma_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_von", DbType="Int")]
		public System.Nullable<int> gia_von
		{
			get
			{
				return this._gia_von;
			}
			set
			{
				if ((this._gia_von != value))
				{
					this.Ongia_vonChanging(value);
					this.SendPropertyChanging();
					this._gia_von = value;
					this.SendPropertyChanged("gia_von");
					this.Ongia_vonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_Nhap", DbType="Int")]
		public System.Nullable<int> SL_Nhap
		{
			get
			{
				return this._SL_Nhap;
			}
			set
			{
				if ((this._SL_Nhap != value))
				{
					this.OnSL_NhapChanging(value);
					this.SendPropertyChanging();
					this._SL_Nhap = value;
					this.SendPropertyChanged("SL_Nhap");
					this.OnSL_NhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_CTHoaDonNhap", Storage="_Thuoc", ThisKey="ma_thuoc", OtherKey="ma_thuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.CTHoaDonNhaps.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.CTHoaDonNhaps.Add(this);
						this._ma_thuoc = value.ma_thuoc;
					}
					else
					{
						this._ma_thuoc = default(string);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonNhap_CTHoaDonNhap", Storage="_HoaDonNhap", ThisKey="maHD_Nhap", OtherKey="maHD_Nhap", IsForeignKey=true)]
		public HoaDonNhap HoaDonNhap
		{
			get
			{
				return this._HoaDonNhap.Entity;
			}
			set
			{
				HoaDonNhap previousValue = this._HoaDonNhap.Entity;
				if (((previousValue != value) 
							|| (this._HoaDonNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDonNhap.Entity = null;
						previousValue.CTHoaDonNhaps.Remove(this);
					}
					this._HoaDonNhap.Entity = value;
					if ((value != null))
					{
						value.CTHoaDonNhaps.Add(this);
						this._maHD_Nhap = value.maHD_Nhap;
					}
					else
					{
						this._maHD_Nhap = default(string);
					}
					this.SendPropertyChanged("HoaDonNhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma_thuoc;
		
		private string _ma_nhom;
		
		private string _ten_thuoc;
		
		private string _cong_dung;
		
		private string _thanh_phan;
		
		private string _xuat_xu;
		
		private string _dvt;
		
		private System.Nullable<int> _gia_ban;
		
		private System.Nullable<int> _so_luong;
		
		private EntitySet<CTHoaDonNhap> _CTHoaDonNhaps;
		
		private EntitySet<CTHoaDonXuat> _CTHoaDonXuats;
		
		private EntityRef<NhomThuoc> _NhomThuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_thuocChanging(string value);
    partial void Onma_thuocChanged();
    partial void Onma_nhomChanging(string value);
    partial void Onma_nhomChanged();
    partial void Onten_thuocChanging(string value);
    partial void Onten_thuocChanged();
    partial void Oncong_dungChanging(string value);
    partial void Oncong_dungChanged();
    partial void Onthanh_phanChanging(string value);
    partial void Onthanh_phanChanged();
    partial void Onxuat_xuChanging(string value);
    partial void Onxuat_xuChanged();
    partial void OndvtChanging(string value);
    partial void OndvtChanged();
    partial void Ongia_banChanging(System.Nullable<int> value);
    partial void Ongia_banChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    #endregion
		
		public Thuoc()
		{
			this._CTHoaDonNhaps = new EntitySet<CTHoaDonNhap>(new Action<CTHoaDonNhap>(this.attach_CTHoaDonNhaps), new Action<CTHoaDonNhap>(this.detach_CTHoaDonNhaps));
			this._CTHoaDonXuats = new EntitySet<CTHoaDonXuat>(new Action<CTHoaDonXuat>(this.attach_CTHoaDonXuats), new Action<CTHoaDonXuat>(this.detach_CTHoaDonXuats));
			this._NhomThuoc = default(EntityRef<NhomThuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_thuoc", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma_thuoc
		{
			get
			{
				return this._ma_thuoc;
			}
			set
			{
				if ((this._ma_thuoc != value))
				{
					this.Onma_thuocChanging(value);
					this.SendPropertyChanging();
					this._ma_thuoc = value;
					this.SendPropertyChanged("ma_thuoc");
					this.Onma_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nhom", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ma_nhom
		{
			get
			{
				return this._ma_nhom;
			}
			set
			{
				if ((this._ma_nhom != value))
				{
					if (this._NhomThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_nhomChanging(value);
					this.SendPropertyChanging();
					this._ma_nhom = value;
					this.SendPropertyChanged("ma_nhom");
					this.Onma_nhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_thuoc", DbType="NVarChar(50)")]
		public string ten_thuoc
		{
			get
			{
				return this._ten_thuoc;
			}
			set
			{
				if ((this._ten_thuoc != value))
				{
					this.Onten_thuocChanging(value);
					this.SendPropertyChanging();
					this._ten_thuoc = value;
					this.SendPropertyChanged("ten_thuoc");
					this.Onten_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cong_dung", DbType="NVarChar(200)")]
		public string cong_dung
		{
			get
			{
				return this._cong_dung;
			}
			set
			{
				if ((this._cong_dung != value))
				{
					this.Oncong_dungChanging(value);
					this.SendPropertyChanging();
					this._cong_dung = value;
					this.SendPropertyChanged("cong_dung");
					this.Oncong_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanh_phan", DbType="NVarChar(200)")]
		public string thanh_phan
		{
			get
			{
				return this._thanh_phan;
			}
			set
			{
				if ((this._thanh_phan != value))
				{
					this.Onthanh_phanChanging(value);
					this.SendPropertyChanging();
					this._thanh_phan = value;
					this.SendPropertyChanged("thanh_phan");
					this.Onthanh_phanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuat_xu", DbType="NVarChar(50)")]
		public string xuat_xu
		{
			get
			{
				return this._xuat_xu;
			}
			set
			{
				if ((this._xuat_xu != value))
				{
					this.Onxuat_xuChanging(value);
					this.SendPropertyChanging();
					this._xuat_xu = value;
					this.SendPropertyChanged("xuat_xu");
					this.Onxuat_xuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dvt", DbType="NVarChar(10)")]
		public string dvt
		{
			get
			{
				return this._dvt;
			}
			set
			{
				if ((this._dvt != value))
				{
					this.OndvtChanging(value);
					this.SendPropertyChanging();
					this._dvt = value;
					this.SendPropertyChanged("dvt");
					this.OndvtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_ban", DbType="Int")]
		public System.Nullable<int> gia_ban
		{
			get
			{
				return this._gia_ban;
			}
			set
			{
				if ((this._gia_ban != value))
				{
					this.Ongia_banChanging(value);
					this.SendPropertyChanging();
					this._gia_ban = value;
					this.SendPropertyChanged("gia_ban");
					this.Ongia_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_CTHoaDonNhap", Storage="_CTHoaDonNhaps", ThisKey="ma_thuoc", OtherKey="ma_thuoc")]
		public EntitySet<CTHoaDonNhap> CTHoaDonNhaps
		{
			get
			{
				return this._CTHoaDonNhaps;
			}
			set
			{
				this._CTHoaDonNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_CTHoaDonXuat", Storage="_CTHoaDonXuats", ThisKey="ma_thuoc", OtherKey="ma_thuoc")]
		public EntitySet<CTHoaDonXuat> CTHoaDonXuats
		{
			get
			{
				return this._CTHoaDonXuats;
			}
			set
			{
				this._CTHoaDonXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomThuoc_Thuoc", Storage="_NhomThuoc", ThisKey="ma_nhom", OtherKey="ma_nhom", IsForeignKey=true)]
		public NhomThuoc NhomThuoc
		{
			get
			{
				return this._NhomThuoc.Entity;
			}
			set
			{
				NhomThuoc previousValue = this._NhomThuoc.Entity;
				if (((previousValue != value) 
							|| (this._NhomThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomThuoc.Entity = null;
						previousValue.Thuocs.Remove(this);
					}
					this._NhomThuoc.Entity = value;
					if ((value != null))
					{
						value.Thuocs.Add(this);
						this._ma_nhom = value.ma_nhom;
					}
					else
					{
						this._ma_nhom = default(string);
					}
					this.SendPropertyChanged("NhomThuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHoaDonNhaps(CTHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_CTHoaDonNhaps(CTHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
		
		private void attach_CTHoaDonXuats(CTHoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_CTHoaDonXuats(CTHoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHoaDonXuat")]
	public partial class CTHoaDonXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD_Xuat;
		
		private string _ma_thuoc;
		
		private System.Nullable<int> _gia_ban;
		
		private System.Nullable<int> _SL_ban;
		
		private EntityRef<Thuoc> _Thuoc;
		
		private EntityRef<HoaDonXuat> _HoaDonXuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHD_XuatChanging(string value);
    partial void OnmaHD_XuatChanged();
    partial void Onma_thuocChanging(string value);
    partial void Onma_thuocChanged();
    partial void Ongia_banChanging(System.Nullable<int> value);
    partial void Ongia_banChanged();
    partial void OnSL_banChanging(System.Nullable<int> value);
    partial void OnSL_banChanged();
    #endregion
		
		public CTHoaDonXuat()
		{
			this._Thuoc = default(EntityRef<Thuoc>);
			this._HoaDonXuat = default(EntityRef<HoaDonXuat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD_Xuat", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD_Xuat
		{
			get
			{
				return this._maHD_Xuat;
			}
			set
			{
				if ((this._maHD_Xuat != value))
				{
					if (this._HoaDonXuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHD_XuatChanging(value);
					this.SendPropertyChanging();
					this._maHD_Xuat = value;
					this.SendPropertyChanged("maHD_Xuat");
					this.OnmaHD_XuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_thuoc", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma_thuoc
		{
			get
			{
				return this._ma_thuoc;
			}
			set
			{
				if ((this._ma_thuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_thuocChanging(value);
					this.SendPropertyChanging();
					this._ma_thuoc = value;
					this.SendPropertyChanged("ma_thuoc");
					this.Onma_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_ban", DbType="Int")]
		public System.Nullable<int> gia_ban
		{
			get
			{
				return this._gia_ban;
			}
			set
			{
				if ((this._gia_ban != value))
				{
					this.Ongia_banChanging(value);
					this.SendPropertyChanging();
					this._gia_ban = value;
					this.SendPropertyChanged("gia_ban");
					this.Ongia_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_ban", DbType="Int")]
		public System.Nullable<int> SL_ban
		{
			get
			{
				return this._SL_ban;
			}
			set
			{
				if ((this._SL_ban != value))
				{
					this.OnSL_banChanging(value);
					this.SendPropertyChanging();
					this._SL_ban = value;
					this.SendPropertyChanged("SL_ban");
					this.OnSL_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_CTHoaDonXuat", Storage="_Thuoc", ThisKey="ma_thuoc", OtherKey="ma_thuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.CTHoaDonXuats.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.CTHoaDonXuats.Add(this);
						this._ma_thuoc = value.ma_thuoc;
					}
					else
					{
						this._ma_thuoc = default(string);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonXuat_CTHoaDonXuat", Storage="_HoaDonXuat", ThisKey="maHD_Xuat", OtherKey="maHD_Xuat", IsForeignKey=true)]
		public HoaDonXuat HoaDonXuat
		{
			get
			{
				return this._HoaDonXuat.Entity;
			}
			set
			{
				HoaDonXuat previousValue = this._HoaDonXuat.Entity;
				if (((previousValue != value) 
							|| (this._HoaDonXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDonXuat.Entity = null;
						previousValue.CTHoaDonXuats.Remove(this);
					}
					this._HoaDonXuat.Entity = value;
					if ((value != null))
					{
						value.CTHoaDonXuats.Add(this);
						this._maHD_Xuat = value.maHD_Xuat;
					}
					else
					{
						this._maHD_Xuat = default(string);
					}
					this.SendPropertyChanged("HoaDonXuat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonNhap")]
	public partial class HoaDonNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD_Nhap;
		
		private string _maNV;
		
		private System.Nullable<System.DateTime> _ngaynhap;
		
		private string _ten_nha_cung_cap;
		
		private System.Nullable<int> _tong_tien;
		
		private EntitySet<CTHoaDonNhap> _CTHoaDonNhaps;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHD_NhapChanging(string value);
    partial void OnmaHD_NhapChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaynhapChanged();
    partial void Onten_nha_cung_capChanging(string value);
    partial void Onten_nha_cung_capChanged();
    partial void Ontong_tienChanging(System.Nullable<int> value);
    partial void Ontong_tienChanged();
    #endregion
		
		public HoaDonNhap()
		{
			this._CTHoaDonNhaps = new EntitySet<CTHoaDonNhap>(new Action<CTHoaDonNhap>(this.attach_CTHoaDonNhaps), new Action<CTHoaDonNhap>(this.detach_CTHoaDonNhaps));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD_Nhap", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD_Nhap
		{
			get
			{
				return this._maHD_Nhap;
			}
			set
			{
				if ((this._maHD_Nhap != value))
				{
					this.OnmaHD_NhapChanging(value);
					this.SendPropertyChanging();
					this._maHD_Nhap = value;
					this.SendPropertyChanged("maHD_Nhap");
					this.OnmaHD_NhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nha_cung_cap", DbType="NVarChar(50)")]
		public string ten_nha_cung_cap
		{
			get
			{
				return this._ten_nha_cung_cap;
			}
			set
			{
				if ((this._ten_nha_cung_cap != value))
				{
					this.Onten_nha_cung_capChanging(value);
					this.SendPropertyChanging();
					this._ten_nha_cung_cap = value;
					this.SendPropertyChanged("ten_nha_cung_cap");
					this.Onten_nha_cung_capChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Int")]
		public System.Nullable<int> tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonNhap_CTHoaDonNhap", Storage="_CTHoaDonNhaps", ThisKey="maHD_Nhap", OtherKey="maHD_Nhap")]
		public EntitySet<CTHoaDonNhap> CTHoaDonNhaps
		{
			get
			{
				return this._CTHoaDonNhaps;
			}
			set
			{
				this._CTHoaDonNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDonNhap", Storage="_NhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDonNhaps.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDonNhaps.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHoaDonNhaps(CTHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonNhap = this;
		}
		
		private void detach_CTHoaDonNhaps(CTHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonNhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonXuat")]
	public partial class HoaDonXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD_Xuat;
		
		private string _maNV;
		
		private string _maKH;
		
		private System.Nullable<System.DateTime> _ngay_xuat;
		
		private System.Nullable<int> _tong_tien;
		
		private EntitySet<CTHoaDonXuat> _CTHoaDonXuats;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHD_XuatChanging(string value);
    partial void OnmaHD_XuatChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void Onngay_xuatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_xuatChanged();
    partial void Ontong_tienChanging(System.Nullable<int> value);
    partial void Ontong_tienChanged();
    #endregion
		
		public HoaDonXuat()
		{
			this._CTHoaDonXuats = new EntitySet<CTHoaDonXuat>(new Action<CTHoaDonXuat>(this.attach_CTHoaDonXuats), new Action<CTHoaDonXuat>(this.detach_CTHoaDonXuats));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD_Xuat", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD_Xuat
		{
			get
			{
				return this._maHD_Xuat;
			}
			set
			{
				if ((this._maHD_Xuat != value))
				{
					this.OnmaHD_XuatChanging(value);
					this.SendPropertyChanging();
					this._maHD_Xuat = value;
					this.SendPropertyChanged("maHD_Xuat");
					this.OnmaHD_XuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="NVarChar(10)")]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_xuat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_xuat
		{
			get
			{
				return this._ngay_xuat;
			}
			set
			{
				if ((this._ngay_xuat != value))
				{
					this.Onngay_xuatChanging(value);
					this.SendPropertyChanging();
					this._ngay_xuat = value;
					this.SendPropertyChanged("ngay_xuat");
					this.Onngay_xuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Int")]
		public System.Nullable<int> tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonXuat_CTHoaDonXuat", Storage="_CTHoaDonXuats", ThisKey="maHD_Xuat", OtherKey="maHD_Xuat")]
		public EntitySet<CTHoaDonXuat> CTHoaDonXuats
		{
			get
			{
				return this._CTHoaDonXuats;
			}
			set
			{
				this._CTHoaDonXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDonXuat", Storage="_KhachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDonXuats.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDonXuats.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDonXuat", Storage="_NhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDonXuats.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDonXuats.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHoaDonXuats(CTHoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonXuat = this;
		}
		
		private void detach_CTHoaDonXuats(CTHoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonXuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _ho_ten;
		
		private string _gioi_tinh;
		
		private System.Nullable<int> _tuoi;
		
		private string _soDT;
		
		private System.Nullable<int> _diem;
		
		private EntitySet<HoaDonXuat> _HoaDonXuats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Ongioi_tinhChanging(string value);
    partial void Ongioi_tinhChanged();
    partial void OntuoiChanging(System.Nullable<int> value);
    partial void OntuoiChanged();
    partial void OnsoDTChanging(string value);
    partial void OnsoDTChanged();
    partial void OndiemChanging(System.Nullable<int> value);
    partial void OndiemChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDonXuats = new EntitySet<HoaDonXuat>(new Action<HoaDonXuat>(this.attach_HoaDonXuats), new Action<HoaDonXuat>(this.detach_HoaDonXuats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(50)")]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="NVarChar(10)")]
		public string gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuoi", DbType="Int")]
		public System.Nullable<int> tuoi
		{
			get
			{
				return this._tuoi;
			}
			set
			{
				if ((this._tuoi != value))
				{
					this.OntuoiChanging(value);
					this.SendPropertyChanging();
					this._tuoi = value;
					this.SendPropertyChanged("tuoi");
					this.OntuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDT", DbType="Char(10)")]
		public string soDT
		{
			get
			{
				return this._soDT;
			}
			set
			{
				if ((this._soDT != value))
				{
					this.OnsoDTChanging(value);
					this.SendPropertyChanging();
					this._soDT = value;
					this.SendPropertyChanged("soDT");
					this.OnsoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem", DbType="Int")]
		public System.Nullable<int> diem
		{
			get
			{
				return this._diem;
			}
			set
			{
				if ((this._diem != value))
				{
					this.OndiemChanging(value);
					this.SendPropertyChanging();
					this._diem = value;
					this.SendPropertyChanged("diem");
					this.OndiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDonXuat", Storage="_HoaDonXuats", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<HoaDonXuat> HoaDonXuats
		{
			get
			{
				return this._HoaDonXuats;
			}
			set
			{
				this._HoaDonXuats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonXuats(HoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDonXuats(HoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _ho_ten;
		
		private string _gioi_tinh;
		
		private System.Nullable<int> _tuoi;
		
		private string _dia_chi;
		
		private string _email;
		
		private string _soDT;
		
		private string _chuc_vu;
		
		private string _ten_DN;
		
		private string _matkhau;
		
		private EntitySet<HoaDonNhap> _HoaDonNhaps;
		
		private EntitySet<HoaDonXuat> _HoaDonXuats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Ongioi_tinhChanging(string value);
    partial void Ongioi_tinhChanged();
    partial void OntuoiChanging(System.Nullable<int> value);
    partial void OntuoiChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsoDTChanging(string value);
    partial void OnsoDTChanged();
    partial void Onchuc_vuChanging(string value);
    partial void Onchuc_vuChanged();
    partial void Onten_DNChanging(string value);
    partial void Onten_DNChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDonNhaps = new EntitySet<HoaDonNhap>(new Action<HoaDonNhap>(this.attach_HoaDonNhaps), new Action<HoaDonNhap>(this.detach_HoaDonNhaps));
			this._HoaDonXuats = new EntitySet<HoaDonXuat>(new Action<HoaDonXuat>(this.attach_HoaDonXuats), new Action<HoaDonXuat>(this.detach_HoaDonXuats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(50)")]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="NVarChar(10)")]
		public string gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuoi", DbType="Int")]
		public System.Nullable<int> tuoi
		{
			get
			{
				return this._tuoi;
			}
			set
			{
				if ((this._tuoi != value))
				{
					this.OntuoiChanging(value);
					this.SendPropertyChanging();
					this._tuoi = value;
					this.SendPropertyChanged("tuoi");
					this.OntuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(200)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDT", DbType="Char(10)")]
		public string soDT
		{
			get
			{
				return this._soDT;
			}
			set
			{
				if ((this._soDT != value))
				{
					this.OnsoDTChanging(value);
					this.SendPropertyChanging();
					this._soDT = value;
					this.SendPropertyChanged("soDT");
					this.OnsoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuc_vu", DbType="NVarChar(50)")]
		public string chuc_vu
		{
			get
			{
				return this._chuc_vu;
			}
			set
			{
				if ((this._chuc_vu != value))
				{
					this.Onchuc_vuChanging(value);
					this.SendPropertyChanging();
					this._chuc_vu = value;
					this.SendPropertyChanged("chuc_vu");
					this.Onchuc_vuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_DN", DbType="NVarChar(20)")]
		public string ten_DN
		{
			get
			{
				return this._ten_DN;
			}
			set
			{
				if ((this._ten_DN != value))
				{
					this.Onten_DNChanging(value);
					this.SendPropertyChanging();
					this._ten_DN = value;
					this.SendPropertyChanged("ten_DN");
					this.Onten_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(20)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDonNhap", Storage="_HoaDonNhaps", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<HoaDonNhap> HoaDonNhaps
		{
			get
			{
				return this._HoaDonNhaps;
			}
			set
			{
				this._HoaDonNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDonXuat", Storage="_HoaDonXuats", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<HoaDonXuat> HoaDonXuats
		{
			get
			{
				return this._HoaDonXuats;
			}
			set
			{
				this._HoaDonXuats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonNhaps(HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDonNhaps(HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HoaDonXuats(HoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDonXuats(HoaDonXuat entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomThuoc")]
	public partial class NhomThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma_nhom;
		
		private string _ten_nhom;
		
		private EntitySet<Thuoc> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_nhomChanging(string value);
    partial void Onma_nhomChanged();
    partial void Onten_nhomChanging(string value);
    partial void Onten_nhomChanged();
    #endregion
		
		public NhomThuoc()
		{
			this._Thuocs = new EntitySet<Thuoc>(new Action<Thuoc>(this.attach_Thuocs), new Action<Thuoc>(this.detach_Thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nhom", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma_nhom
		{
			get
			{
				return this._ma_nhom;
			}
			set
			{
				if ((this._ma_nhom != value))
				{
					this.Onma_nhomChanging(value);
					this.SendPropertyChanging();
					this._ma_nhom = value;
					this.SendPropertyChanged("ma_nhom");
					this.Onma_nhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nhom", DbType="NVarChar(50)")]
		public string ten_nhom
		{
			get
			{
				return this._ten_nhom;
			}
			set
			{
				if ((this._ten_nhom != value))
				{
					this.Onten_nhomChanging(value);
					this.SendPropertyChanging();
					this._ten_nhom = value;
					this.SendPropertyChanged("ten_nhom");
					this.Onten_nhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomThuoc_Thuoc", Storage="_Thuocs", ThisKey="ma_nhom", OtherKey="ma_nhom")]
		public EntitySet<Thuoc> Thuocs
		{
			get
			{
				return this._Thuocs;
			}
			set
			{
				this._Thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhomThuoc = this;
		}
		
		private void detach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.NhomThuoc = null;
		}
	}
}
#pragma warning restore 1591
